# https://taskfile.dev
# yaml-language-server: $schema=https://taskfile.dev/schema.json

version: 3

tasks:
  bench:
    desc: Run benchmarks
    cmd: "go test -bench=BenchmarkLogger -benchmem"
  test:
    desc: Run tests
    cmd: "go test -cover"
  docs:
    desc: Preview docs
    cmd: "go doc -http"
